- name: Codecov
  uses: codecov/codecov-action@v3.1.1
  codecov:
  token: 84583b03-1fa1-41c1-99d8-f89557dcfdba
 
 
coverage:
  precision: 5
  round: down
  range: "70...100"
  notify:
    # notification blocks. See: https://docs.codecov.io/docs/codecovyml-reference#section-coverage-notify
  status:
    project:
    patch:
    changes:
